[package]
name = "rf-106-dsp"
description = "Portable no_std RF-106 synthesis engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
libm = "0.2"
rf-106-chorus.workspace = true
rf-106-control.workspace = true
rf-106-output.workspace = true
rf-106-voice.workspace = true
rf-106-contract.workspace = true

[dev-dependencies]
hound.workspace = true
